### ISSUE TITLE
Error on running servonk on Nexus 5 device

### ISSUE THREAD

**Issue by arunkumar413** [fabricedesre/servonk#18]
Hi Team,

I had flashed the Nexus 5 device. However when I run the command ./servonk run gonk  I'm getting the below error. Also here is my git log: 

```
arun@devilbox ~/Documents/servonk $ git log | head
commit a7082e6c7294109d002c663db1208727ad6653fa
Merge: 9350561 3ea68e2
Author: arunkumar413 <arunkumar413@gmail.com>
Date:   Tue May 22 20:22:00 2018 +0530

    latest update Merge branch 'master' of https://github.com/fabricedesre/servonk into arun

commit 3ea68e2c38a802f584efbcc738796093d89dcc08
Author: Fabrice Desré <fabrice@desre.org>
Date:   Mon May 21 15:01:39 2018 -0700
arun@devilbox ~/Documents/servonk $
```

```
arun@devilbox ~/Documents/servonk $ ./servonk run gonk
Options configured as None Some(1.0) false
thread 'ResourceManager' panicked at 'Can't read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
thread 'main' panicked at 'Can't read file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: __libc_init
thread 'StorageManager' panicked at 'called `Result::unwrap()` on an `Err` value: Io(Custom { kind: ConnectionReset, error: StringError("MPSC channel sender closed") })', libcore/result.rs:945:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
arun@devilbox ~/Documents/servonk $ ./servonk run gonk
```

**Comment by fabricedesre** [comment]
Is that still happening?

**Comment by arunkumar413** [comment]
No, it's not happening. Seems like this occurred because of display not being closed or opened correctly. You can close this
